version: 2.1
jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.1-node
        environment:
          DB_HOST: localhost
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_DB: myapp_test
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: |
            sudo apt update
            sudo apt install bundler
      - run:
          name: Bundle Install
          command: |
            bundle install
      - run:
          name: DBの起動まで待機
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # - run:
      #     name: "環境変数の確認"
      #     command: psql -h localhost -p 5432 -U postgres -d myapp_test
      - run:
          name: "rspec"
          command: "bundle exec rspec"
workflows:
  build_and_analyze:
    jobs:
      - rspec
