version: 2.1
jobs:
  rspec:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "rspec"
          command: "bundle exec rspec"
workflows:
  build_and_analyze:
    jobs:
      - rspec
