version: 2.1
jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.1-node
      - image: circleci/postgres:12-alpine
        environment:
           POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: |
            sudo apt update
            sudo apt install bundler
      - run:
          name: Bundle Install
          command: |
            bundle install
      - run:
          name: "rspec"
          command: "bundle exec rspec"
workflows:
  build_and_analyze:
    jobs:
      - rspec
