version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  rspec:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: |
            sudo apt update
            sudo apt install bundler
      - run:
          name: Bundle Install
          command: |
            bundle install
      - run:
          name: "rspec"
          command: "bundle exec rspec"
workflows:
  build_and_analyze:
    jobs:
      - rspec
